query getConnectionRequest($data: GetConnectionRequestDto!){
    getConnectionRequest(data: $data){
        id
        to{
            id
            email
            username
            avatarPath
            isVerified
            isBanned
            forgotPasswordLock
            bio
            phoneNumber
            password
            firstName
            lastName
            status
            connections{
                id
                email
                username
                avatarPath
                isVerified
                isBanned
                forgotPasswordLock
                bio
                phoneNumber
                password
                firstName
                lastName
                status
                connections{
                    id
                    email
                    username
                    avatarPath
                    isVerified
                    isBanned
                    forgotPasswordLock
                    bio
                    phoneNumber
                    password
                    firstName
                    lastName
                    status
                    conversations{
                        id
                        createdAt
                    }
                    conversationsCount
                    connectionsCount
                    name
                }
                conversationsCount
                connectionsCount
                name
            }
            conversations{
                id
                createdAt
                participants{
                    id
                    email
                    username
                    avatarPath
                    isVerified
                    isBanned
                    forgotPasswordLock
                    bio
                    phoneNumber
                    password
                    firstName
                    lastName
                    status
                    connections{
                        id
                        email
                        username
                        avatarPath
                        isVerified
                        isBanned
                        forgotPasswordLock
                        bio
                        phoneNumber
                        password
                        firstName
                        lastName
                        status
                        conversationsCount
                        connectionsCount
                        name
                    }
                    conversations{
                        id
                        createdAt
                    }
                    conversationsCount
                    connectionsCount
                    name
                }
                messages{
                    id
                    sender{
                        id
                        email
                        username
                        avatarPath
                        isVerified
                        isBanned
                        forgotPasswordLock
                        bio
                        phoneNumber
                        password
                        firstName
                        lastName
                        status
                        conversationsCount
                        connectionsCount
                        name
                    }
                    message
                    unread
                    createdAt
                }
            }
            conversationsCount
            connectionsCount
            name
        }
        read
        label
        createdAt
        from{
            id
            email
            username
            avatarPath
            isVerified
            isBanned
            forgotPasswordLock
            bio
            phoneNumber
            password
            firstName
            lastName
            status
            connections{
                id
                email
                username
                avatarPath
                isVerified
                isBanned
                forgotPasswordLock
                bio
                phoneNumber
                password
                firstName
                lastName
                status
                conversationsCount
                connectionsCount
                name
            }
            conversations{
                id
                createdAt
            }
            conversationsCount
            connectionsCount
            name
        }
        status
    }
}