query getConnectionRequest($data: GetConnectionRequestDto!){
    getConnectionRequest(data: $data){
        id
        to{
            id
            email
            username
            avatarPath
            isVerified
            isBanned
            forgotPasswordLock
            bio
            phoneNumber
            password
            firstName
            lastName
            status
            connections{
                id
                email
                username
                avatarPath
                isVerified
                isBanned
                forgotPasswordLock
                bio
                phoneNumber
                password
                firstName
                lastName
                status
                connections{
                    id
                    email
                    username
                    avatarPath
                    isVerified
                    isBanned
                    forgotPasswordLock
                    bio
                    phoneNumber
                    password
                    firstName
                    lastName
                    status
                    connectionsCount
                    name
                }
                connectionsCount
                name
            }
            connectionsCount
            name
        }
        read
        label
        createdAt
        from{
            id
            email
            username
            avatarPath
            isVerified
            isBanned
            forgotPasswordLock
            bio
            phoneNumber
            password
            firstName
            lastName
            status
            connections{
                id
                email
                username
                avatarPath
                isVerified
                isBanned
                forgotPasswordLock
                bio
                phoneNumber
                password
                firstName
                lastName
                status
                connectionsCount
                name
            }
            connectionsCount
            name
        }
        status
    }
}