query getUser($data: GetUserDto!){
    getUser(data: $data){
        id
        email
        username
        isVerified
        isBanned
        phoneNumber
        password
        firstName
        lastName
        status
        name
    }
}