query me{
    me{
        id
        email
        username
        avatarPath
        isVerified
        isBanned
        forgotPasswordLock
        bio
        phoneNumber
        password
        firstName
        lastName
        status
        followers{
            id
            email
            username
            avatarPath
            isVerified
            isBanned
            forgotPasswordLock
            bio
            phoneNumber
            password
            firstName
            lastName
            status
            followers{
                id
                email
                username
                avatarPath
                isVerified
                isBanned
                forgotPasswordLock
                bio
                phoneNumber
                password
                firstName
                lastName
                status
                following{
                    id
                    email
                    username
                    avatarPath
                    isVerified
                    isBanned
                    forgotPasswordLock
                    bio
                    phoneNumber
                    password
                    firstName
                    lastName
                    status
                    followers{
                        id
                        email
                        username
                        avatarPath
                        isVerified
                        isBanned
                        forgotPasswordLock
                        bio
                        phoneNumber
                        password
                        firstName
                        lastName
                        status
                        followersCount
                        followingCount
                        name
                    }
                    following{
                        id
                        email
                        username
                        avatarPath
                        isVerified
                        isBanned
                        forgotPasswordLock
                        bio
                        phoneNumber
                        password
                        firstName
                        lastName
                        status
                        followersCount
                        followingCount
                        name
                    }
                    followersCount
                    followingCount
                    name
                }
                followersCount
                followingCount
                name
            }
            followersCount
            followingCount
            name
        }
        following{
            id
            email
            username
            avatarPath
            isVerified
            isBanned
            forgotPasswordLock
            bio
            phoneNumber
            password
            firstName
            lastName
            status
            followersCount
            followingCount
            name
        }
        followersCount
        followingCount
        name
    }
}