query me{
    me{
        id
        email
        username
        isVerified
        isBanned
        forgotPasswordLock
        bio
        phoneNumber
        password
        firstName
        lastName
        status
        name
    }
}