version: "3.7"

services:
  redis:
    container_name: "redis"
    image: redis:alpine
    ports:
      - 6379:6379

  db:
    image: postgres
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: Cqt20011101
    ports:
      - 5432:5432

  node:
    image: "ramen/topping:1.0"
    depends_on:
      - db
      - redis
    ports:
      - 5000:5000
