export enum CustomMessage {
	accountIsNotRegister = "This account is not register yet",
	passwordIsNotMatch = "Password is not match",
	inValidEmailAddress = "Invalid email address",
	emailIsRegister = "Email is already registered",
	conversationIdIsNotValid = "Conversation ID is not valid",
	conversationHasBeenCreated = "Conversation has been created",
	conversationIsNotExist = "This conversation is not exist",
	userIsNotOwner = "You are not the conversation owner",
	userIsNotFound = "User is not Found",
	userHasLoggedIn = "You have already logged in",
	usernameIsTaken = "Username has been taken already",
	userIsBanned = "Your account is banned",
	userIsNotVerified = "Your account is not verified yet",
	phoneNumberIsTaken = "Phone Number is taken",
	expiredKeyError = "Key has expired",
	hmmm___err = "Hmmmm...This doesn't seem right",
	connectionRequestIsSended = "Your request has been sent already!",
	connectionRequestIsNotExist = "Sorry, we can not found the request",
	connectionRequestAuthorized = "This is not your connection request",
}
